import {StyleSheet} from 'react-native';

export default StyleSheet.create({
  section__title: {
    marginLeft: 30,
    marginTop: 30,
  },
  Section__title__desc: {
    fontSize: 15,
    color: '#A0A3BD',
  },
  section__title__desc__title: {
    fontSize: 48,
    color: '#5F2EEA',
  },
  section__img: {
    flex: 3,
    display: 'flex',
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    marginLeft: '0%',
  },
  section__img__container1: {
    borderRadius: 10,
    marginLeft: '3%',
    position: 'relative',
    overflow: 'hidden',
    boxShadow: '5 5 20 2 rgba(0, 0, 0, 0.3)',
    width: 85,
    height: 281,
    marginTop: '7%',
    marginBottom: '0%',
  },
  section__img__container2: {
    borderRadius: 10,
    marginLeft: '3%',
    position: 'relative',
    overflow: 'hidden',
    boxShadow: '5 5 20 2 rgba(0, 0, 0, 0.3)',
    width: 85,
    height: 281,
    marginTop: '7%',
    marginBottom: '10%',
  },
  section__img__container3: {
    borderRadius: 10,
    marginLeft: '3%',
    position: 'relative',
    overflow: 'hidden',
    boxShadow: '5 5 20 2 rgba(0, 0, 0, 0.3)',
    width: 85,
    height: 281,
    marginTop: '7%',
    marginBottom: '20%',
  },
  section__img__overlay: {
    position: 'absolute',
    background: 'rgba(0, 0, 0, 0.3)',
  },
  main1__title: {
    paddingHorizontal: 30,
    display: 'flex',
    justifyContent: 'space-between',
    paddingBottom: 30,
    flexDirection: 'row',
  },
  main1__img__container__hover: {
    marginTop: 20,
  },
  main1__img__container__hover__viewall: {
    marginTop: 20,
  },
  main1__img__hover: {
    // height: 370,
    width: 200,
    backgroundColor: 'rgba(255, 255, 255, 0.2)',
    border: '2 solid #ffffff',
    borderRadius: 8,
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    // marginRight: 10,
    flexDirection: 'column',
    paddingBottom: 10,
    // marginVertical: 10,
    marginBottom: 10,
  },
  main1__month: {
    height: 30,
    width: 75,
    // paddingHorizontal: 20,
    // paddingVertical: 20,
    display: 'flex',
    justifyContent: 'center',
    alignItems: 'center',
    border: 2,
    borderRadius: 7,
    fontSize: 14,
    backgroundColor: '#5f2eea',
    marginLeft: 7,
  },
  main1__month__text: {
    color: 'rgba(247, 247, 252, 1)',
  },
  main1__img__desc: {
    marginTop: 20,
    fontSize: 15,
    lineHeight: 22,
    textAlign: 'center',
    letterSpacing: 0.15,
    color: '#14142b',
  },
  main1__img__desc__2: {
    marginTop: 5,
    marginBottom: 5,
    fontWeight: '400',
    fontSize: 12,
    lineHeight: 16,
    textAlign: 'center',
    letterSpacing: 0.4,
    color: '#a0a3bd',
  },
  footer__subscription: {
    textAlign: 'center',
    boxShadow: '0 16 32 rgba(186, 186, 186, 0.3)',
    borderRadius: 8,
    display: 'flex',
    justifyContent: 'center',
    alignItems: 'center',
    flexDirection: 'column',
    height: 250,
    marginTop: 10,
    marginBottom: 0,
  },
  footer__subscription__text__up1: {
    fontSize: 17,
    color: '#4e4b66',
    textAlign: 'center',
  },
  footer__subscription__text__up2: {
    fontSize: 33,
    color: '#5f2eea',
    textAlign: 'center',
  },
  footer__subscription__submit__input: {
    width: 306,
    height: 43,
    borderWidth: 0.5,
    borderRadius: 10,
    marginBottom: 10,
  },
  footer__subscription__text__down: {
    width: '75%',
    fontWeight: '400',
    fontSize: 14,
    lineHeight: 20,
    marginTop: 20,
    marginBottom: 20,
    textAlign: 'center',
  },
  footer__ending: {
    display: 'flex',
    paddingTop: 50,
    flexDirection: 'column',
    marginHorizontal: 30,
  },
  footer__ending__tickitz: {
    flex: 1.25,
    fontWeight: '400',
    fontSize: 16,
    lineHeight: 22,
    letterSpacing: 0.75,
    color: '#6e7191',
  },
  footer__ending__tickitz__img: {
    width: 100,
    height: 30,
    marginBottom: 20,
  },
  footer__ending__explore__h3: {
    fontWeight: '400',
    fontSize: 14,
    lineHeight: 20,
    letterSpacing: 0.5,
    color: '#000000',
    marginVertical: 15,
  },
  footer__ending__sponsor__list: {
    display: 'flex',
    flexDirection: 'row',
  },
  footer__ending__sponsor__list__img1: {
    height: 25,
    width: 70,
    marginRight: 15,
  },
  footer__ending__sponsor__list__img2: {
    height: 20,
    width: 140,
    marginRight: 15,
  },
  footer__ending__sponsor__list__img3: {
    height: 30,
    width: 100,
  },
  footer__ending__socialMedia__list__div: {
    marginBottom: 15,
    display: 'flex',
    flexDirection: 'row',
  },
  footer__copyright: {
    textAlign: 'center',
    fontWeight: '400',
    fontSize: 14,
    lineHeight: 18,
    letterSpacing: 0.5,
    color: '#4e4b66',
    paddingLeft: 30,
    paddingVertical: 20,
  },
});
